animation by sprite names #1076
craftyjs/Crafty pull request #1091
Opened 2017-03-12 18:34 UTC by maciekwie

I've changed the way `Sprite.sprite()` is called in  `._updateSprite()` method so `reel.frames` can be list of sprite names.

I've added `.reelFrame()` method for setting frame with specified sprite.

// It's my first pull request

2017-03-12 21:05 UTC, starwed requested changes
The code looks good, and thanks for adding tests!

I added some notes for a couple of small style issues, but once those are fixed this is good to merge.

2017-03-12 21:05 UTC, starwed commented on src/graphics/sprite-animation.js
> +            throw("No active reel.");
Could you either put this (and a couple of similar clauses) either in a single line, or explicitly wrap the block in brackets?  The standard approach is 
 
```
if (condition) {
  doSingleThing();
}
```

The idea here is that by omitting brackets, you tempt someone later to do this:
```
if(condition)
   doSomething();
   doSomethingElse();
```
which will not work as expected.  If you have a very short statement, it's also ok to use a single line to make the code a little less noisy, since it doesn't tempt folk the way an indented block does.  :)
```
if (condition) doSomething();
```

2017-03-12 21:05 UTC, starwed commented on src/graphics/sprite-animation.js
> +            this.sprite(frame[0], frame[1]); // .sprite will trigger redraw
Another block needing brackets.

2017-03-12 21:05 UTC, starwed commented on playgrounds/animation/sprite-animation.html
> +                                <option value="countEven_names">Count Even (frame names)</option>
Tiny nit: the indentation here is off.

2017-03-13 10:18 UTC, maciekwie commented
Thank you for feedback!

I've changed conditions according to this rule in the whole file, for consistency.

In `sprite-animation.html` indentation was made with two tabs instead of two spaces, now it's fixed.

2017-03-14 01:43 UTC, starwed approved these changes

2017-03-14 01:46 UTC, starwed commented
Merged into develop -- thanks for the PR!

(I rebased locally to squash down to a single commit, so closing the github PR -- it is merged, though.)

2017-03-14 01:46 UTC, closed without merging